name: Docker
on:
  push:
    branches:
      - master
    tags:
      - 'v*'
      - 'yarn-wasm-rust-build-image-v*'
  pull_request:
    branches:
      - 'master'
  workflow_dispatch:

jobs:
  docker:
    name: "Build a docker image"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v3
        with:
          tags: |
            type=semver,pattern={{version}}
            type=sha
            type=schedule
            type=ref,event=branch
            type=ref,event=tag
            type=ref,event=pr
          # list of Docker images to use as base name for tags
          images: |
            ghcr.io/rbtying/yarn-wasm-rust-build-image
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: arm64,arm
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Cache Docker Layers
        uses: actions/cache@v4
        with:
          path: yarn-wasm-rust-build-image
          key: ${{ runner.os }}-yarn-wasm-rust-build-image

      - name: Login to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha
